--------------------------------------------------------
--  File created - Wednesday-November-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "IDOL"."CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1001 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "IDOL"."CATEGORY" 
   (	"ID" VARCHAR2(10 CHAR), 
	"NAME" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IDOL
--------------------------------------------------------

  CREATE TABLE "IDOL"."IDOL" 
   (	"ID" VARCHAR2(10 CHAR), 
	"BIRTHDAY" DATE, 
	"BIRTHPLACE" VARCHAR2(50 CHAR), 
	"NAME" VARCHAR2(50 CHAR), 
	"CATEGORY_ID" VARCHAR2(10 CHAR), 
	"IMAGE" CLOB, 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into IDOL.CATEGORY
SET DEFINE OFF;
Insert into IDOL.CATEGORY (ID,NAME) values ('01','Blackpink in your Area');
Insert into IDOL.CATEGORY (ID,NAME) values ('02','Football');
Insert into IDOL.CATEGORY (ID,NAME) values ('03','Sim s? ??p');
Insert into IDOL.CATEGORY (ID,NAME) values ('04','?i?n ?nh');
REM INSERTING into IDOL.IDOL
SET DEFINE OFF;
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('9999',to_date('11-FEB-97','DD-MON-RR'),'New Zealand','Rosé','01');
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('8888',to_date('03-JAN-95','DD-MON-RR'),'Hàn Qu?c','Jisoo','01');
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('5555',to_date('24-JUN-87','DD-MON-RR'),'Argentina','Messi','02');
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('4444',to_date('05-FEB-85','DD-MON-RR'),'B? ?ào Nha','Ronaldo','02');
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('3333',to_date('05-FEB-92','DD-MON-RR'),'Brazil','Neymar','02');
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('7777',to_date('16-JAN-96','DD-MON-RR'),'Hàn Qu?c','Jennie','01');
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('6666',to_date('27-MAR-97','DD-MON-RR'),'Thái Lan','Lisa','01');
Insert into IDOL.IDOL (ID,BIRTHDAY,BIRTHPLACE,NAME,CATEGORY_ID) values ('2222',to_date('01-OCT-02','DD-MON-RR'),'B?c Giang','Tr?n ??c M?nh','03');
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "IDOL"."CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IDOL"."CATEGORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IDOL
--------------------------------------------------------

  ALTER TABLE "IDOL"."IDOL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IDOL"."IDOL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IDOL
--------------------------------------------------------

  ALTER TABLE "IDOL"."IDOL" ADD CONSTRAINT "FKB5W6S1IYQ5LKAH5EFWXX0FBGU" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "IDOL"."CATEGORY" ("ID") ENABLE;
